name: My Assistant CD Run - DEV
run-name: My assistant CD Run - DEV
on:
    push:
        branches:
            - dev
        paths:
            - "!*"
            - "my_assistant/**"
            - ".github/workflows/dev.yaml"
permissions:
    id-token: write
    contents: read
    pull-requests: write

defaults:
    run:
        working-directory: .

jobs:
    build_and_run_my_assistant_service:
        runs-on: ubuntu-latest
        # strategy:
        #     matrix:
        #         env: ["dev"]
        # environment: ${{ matrix.env }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: gavan777
                password: dckr_pat_1FyJzUyWEI-lJ0WYGyEgzr6FOGc

            - name: Build & Push Container Image
              shell: bash
              run: |
                  docker image build -t "gavan777/my-assistant:${{ github.sha }}" .
                  docker image push "gavan777/my-assistant:${{ github.sha }}"
                #  docker -H 44.214.99.189 run -d my-assistant-app:${{ github.sha }}
                #   docker push "${{ vars.CLARITY_DOCKER_REGISTRY }}/platform/clarity-statements-service:${{ github.sha }}"

